### ISSUE TITLE
Kréta ügyintézés

### ISSUE THREAD

**Issue by Sasszem** [Verseghy/website_frontend#457]
### Fejlesztők:
Legyen a kréta menüpont egy lenyitható menü mint a többi menüpont és a két item benne legyen "E-Napló" és "E-Ügyintézés". Az enapló linkeljen `target _blank`-kel a mostani enaplóra az ügyintézés szintén `target _blank`-el a https://eugyintezes.e-kreta.hu/ -ra. Kerüljön a footerbe új block "Kréta" névvel  (a hírlevél helyett, de nem teljesen eltörölve azt, csak kikommentelve) és legyen a két oldal szintén belinkelve oda is monochrome ikonokkal együtt.

### QA
Ellenőrizni hogy a menüben működnek-e a linkek és jó helyre visznek. Ellenőrizni hogy az eredeti specifikációnak megfelel-e az implementációnk.

**Comment by Sasszem** [comment]
A kréta ügyintézős logót a jelenlegi honlapról lopjam át?

**Comment by TwoDCube** [comment]
Mindkét logót leszedheted a régi oldalról igen.

**Comment by Sasszem** [comment]
PR: #523
