### ISSUE TITLE
Colleagues page is not responsive

### ISSUE THREAD

**Issue by Sasszem** [Verseghy/website_frontend#485]
Hide `.sidebar` under 992px

**Comment by Sasszem** [comment]
Lehetne pontosítani a feladatot?

**Comment by TwoDCube** [comment]
A colleauges page-en az a sidebar csak gépen néz ki jól kisebb képernyőn tűnjön el. A descriptionben le van írva honnantól

**Comment by Sasszem** [comment]
A sidebar ráadásul nem is működik...
