### ISSUE TITLE
Colleagues page sidebar is not working

### ISSUE THREAD

**Issue by Sasszem** [Verseghy/website_frontend#524]
I also get tons of errors `TypeError: "jit_unwrapValue_1_13(...) is null"` @ `ColleaguesComponent.html:6:8`

**Comment by Sasszem** [comment]
Done scroll-to card via sidebar.
Looks like `_scrollHandler()` is not called on scrolling, only once.

**Comment by TwoDCube** [comment]
In my opinion the whole colleauges should be rewritten into ngrx state management. And then we would handle scrolling as a side effect. What do you think? It would simplify things and make it more readable. The original code was written really early when the goal was to show something not to make it easy to maintain. If you agree we should design the structure of it in this issue.

**Comment by Sasszem** [comment]
Well, if we have the time, then OK, but I was told we're in a hurry.

**Comment by TwoDCube** [comment]
Being in a hurry doesn't mean that we should develop these features as fast as we can. We still need to produce quality code. I'll create two separate issues for this. One for the state management and one for the scrolling issue. I just realized that it would be easier to manage scrolling with an `IntersectionObserver`, so please ignore my previous suggestion about handling scrolling with side effects. That's a bad practice no one should use.
